/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.SQLPhieuMuon;
import Controller.SQLThietBi;
import Model.PhieuMuon;
import Model.ThietBi;
import java.awt.print.PrinterJob;
import static java.awt.print.PrinterJob.getPrinterJob;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author An Vi
 */
public class QLPhieuMuonPanel extends javax.swing.JPanel {

    ArrayList<PhieuMuon> list;
    SQLPhieuMuon sql ;
    DefaultTableModel model;
    private String loaiTK;
    public QLPhieuMuonPanel(String loaiTK) {
        initComponents();
        loaiTK = loaiTK ;
        sql = new SQLPhieuMuon(loaiTK);
        list = sql.getList();
        model = (DefaultTableModel) jTable1.getModel();
        showTable();
    }
    public void showTable() {
        for (PhieuMuon s : list) {
            model.addRow(new Object[]{
                s.getMAPM(), s.getMAPHG(), s.getTHOIDIEMMUON(),s.getHANTRA(),s.getTHOIDIEMTRA(),s.getNGUOILAPPHIEU()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonThoat = new javax.swing.JButton();
        jButtonThem = new javax.swing.JButton();
        jButtonSua = new javax.swing.JButton();
        jButtonXoa = new javax.swing.JButton();
        jButtonTaiLai = new javax.swing.JButton();
        jButtonBaoCao = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf6 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DANH SÁCH PHIẾU MƯỢN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1500, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Mã Phiếu mượn :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        tf1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 270, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Thời điểm mượn:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        tf3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 270, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Mã Phòng :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, -1, -1));

        tf2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 270, 40));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("Hạn trả :");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 180, -1, -1));

        tf4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 170, 270, 40));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã phiếu mượn", "Mã Phòng", "Thời điểm mượn", "Hạn trả", "Thời điểm trả", "Người lập phiếu"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDragEnabled(true);
        jTable1.setRowHeight(40);
        jTable1.setRowSelectionAllowed(false);
        jTable1.setSelectionForeground(new java.awt.Color(255, 0, 0));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.setShowGrid(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 1500, 250));

        jButtonThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonThoat.setText("Thoát");
        jButtonThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThoatActionPerformed(evt);
            }
        });
        add(jButtonThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 350, -1, 60));

        jButtonThem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonThem.setText("Thêm");
        jButtonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemActionPerformed(evt);
            }
        });
        add(jButtonThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, 60));

        jButtonSua.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonSua.setText("Sửa");
        jButtonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaActionPerformed(evt);
            }
        });
        add(jButtonSua, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 350, -1, 60));

        jButtonXoa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonXoa.setText("Xóa");
        jButtonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaActionPerformed(evt);
            }
        });
        add(jButtonXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, 60));

        jButtonTaiLai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonTaiLai.setText("Làm mới");
        jButtonTaiLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaiLaiActionPerformed(evt);
            }
        });
        add(jButtonTaiLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, -1, 60));

        jButtonBaoCao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButtonBaoCao.setText("Báo cáo");
        jButtonBaoCao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaoCaoActionPerformed(evt);
            }
        });
        add(jButtonBaoCao, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, -1, 60));

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton8.setText("Hủy");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 350, -1, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Thời điểm trả :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        tf5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 270, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Người lập phiếu:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 270, -1, -1));

        tf6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 270, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonThoatActionPerformed

    private void jButtonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemActionPerformed
//        ThietBi s = new ThietBi();
//        s.setMaTB(tf1.getText());
//        s.setMaKhu(tf2.getText());
//        s.setLoaiTB(tf3.getText());
//        s.setTinhTrang(Integer.parseInt(tf4.getText()));;
//
//        try {
//            if(sql.addThietBi(s)){
//                JOptionPane.showMessageDialog(this, "Thêm sản phẩm thành công !!");
//                list.add(s); 
//                showResult();
//            } 
//            else{
//                JOptionPane.showMessageDialog(this, "Lỗi !!");
//            }   
//        }catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Lỗi !!");
//        }
//        TaiLaiTrang();
    }//GEN-LAST:event_jButtonThemActionPerformed
    int index = -1;
    private void jButtonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaActionPerformed
        index = jTable1.getSelectedRow() ;
//        ThietBi c = null ;
//        if(index == -1){
//            JOptionPane.showMessageDialog(this, "Hãy chọn sản phẩm muốn chỉnh sửa!!!");
//        }
//        else{
//            c = list.get(index);
//        }
//        
//        ThietBi s = new ThietBi();
//        s.setMaTB(tf1.getText());
//        s.setMaKhu(tf2.getText());
//        s.setLoaiTB(tf3.getText());
//        s.setTinhTrang(Integer.parseInt(tf4.getText()));;
//
//        try {
//            sql.EditThietBi(s);
//            JOptionPane.showMessageDialog(this, "Sửa sản phẩm thành công!!!!");
//            list.remove(index);
//            list.add(index,s); 
//            model.removeRow(index);
//            model.insertRow(index,new Object[]{
//                 tf1.getText(), tf2.getText(), tf3.getText(), tf4.getText()
//            });
//            model.fireTableDataChanged();
//        }catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Lỗi!!!Không thể sửa sản phẩm");
//        }
//        TaiLaiTrang();
        
    }//GEN-LAST:event_jButtonSuaActionPerformed

    private void jButtonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaActionPerformed
//        index = jTable1.getSelectedRow() ;
//        if(list.size() == 0){
//            JOptionPane.showMessageDialog(this, "Hãy nhập kho sản phẩm!!!");
//        }
//        else if(index == -1){
//            JOptionPane.showMessageDialog(this, "Hãy chọn sản phẩm muốn xóa!!!");
//        }
//        else{
//            ThietBi s = list.get(index);
//            try {
//                if(sql.DeleteThietBi(s)){
//                    JOptionPane.showMessageDialog(this, "Xóa sản phẩm thành công!!!!");
//                    list.remove(s);
//                    model.removeRow(index);
//                    model.fireTableDataChanged();
//                } 
//                else{
//                    JOptionPane.showMessageDialog(this, "Lỗi !!! Không thể xóa sản phẩm");
//                }   
//            }catch (Exception ex) {
//                JOptionPane.showMessageDialog(this, "Lỗi !!! Không thể xóa sản phẩm");
//            }
//            TaiLaiTrang();
//        }
    }//GEN-LAST:event_jButtonXoaActionPerformed

    private void jButtonTaiLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaiLaiActionPerformed
        TaiLaiTrang();
    }//GEN-LAST:event_jButtonTaiLaiActionPerformed

    private void jButtonBaoCaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaoCaoActionPerformed
        MessageFormat header = new MessageFormat("Danh sách Thiết bị");
        MessageFormat footer = new MessageFormat("");
        try {
            this.jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Unable to print");
        }
    }//GEN-LAST:event_jButtonBaoCaoActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        index = jTable1.getSelectedRow() ;
        PhieuMuon s = list.get(index);
        tf1.setText(""+s.getMAPM());
        tf2.setText(""+s.getMAPHG());
        tf3.setText(""+s.getTHOIDIEMMUON());
        tf4.setText(""+s.getHANTRA());
        tf5.setText(""+s.getTHOIDIEMTRA());
        tf6.setText(""+s.getNGUOILAPPHIEU());
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void TaiLaiTrang(){
        tf3.setText("");
        tf2.setText("");
        tf1.setText("");
        tf4.setText("");
        jTable1.clearSelection();
    }
    public void showResult() {
//        ThietBi s = list.get(list.size() - 1);
//        model.addRow(new Object[]{
//            tf1.getText(), tf2.getText(), tf3.getText(), tf4.getText()
//        });
//        model.fireTableDataChanged();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButtonBaoCao;
    private javax.swing.JButton jButtonSua;
    private javax.swing.JButton jButtonTaiLai;
    private javax.swing.JButton jButtonThem;
    private javax.swing.JButton jButtonThoat;
    private javax.swing.JButton jButtonXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    // End of variables declaration//GEN-END:variables
}
