/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.SQLLogin;
import Model.LoginAccount;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author An Vi
 */
public class RegisterJFrame extends javax.swing.JFrame {

    Container cont = this.getContentPane();
    private SQLLogin sql;
    private ArrayList<LoginAccount> list;
    public RegisterJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        sql = new SQLLogin("Main");
        list = sql.getListDangNhap();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_usename = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        b_login = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tf_pass1 = new javax.swing.JPasswordField();
        tf_pass = new javax.swing.JPasswordField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng ký");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý thiết bị trường Đại học");
        jLabel1.setToolTipText("");
        jLabel1.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setIconTextGap(10);
        jLabel1.setName(""); // NOI18N
        jLabel1.setNextFocusableComponent(this);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 706, 50));

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Công nghệ thông tin và Truyền thông Việt - Hàn");
        jLabel3.setToolTipText("");
        jLabel3.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setIconTextGap(10);
        jLabel3.setName(""); // NOI18N
        jLabel3.setNextFocusableComponent(this);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 706, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Phân quyền      :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 311, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Tên đăng nhập : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 133, -1, -1));

        tf_usename.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(tf_usename, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 121, 310, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Mật khẩu         :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 192, -1, -1));

        combobox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main", "KhuK", "KhuV" }));
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 299, 310, 40));

        b_login.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        b_login.setText("Đăng ký");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });
        jPanel1.add(b_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 357, 137, 39));

        jLabel7.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel7.setText("Đã có tài khoản, đăng nhập tại đây !!");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 408, 245, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Nhập lại MK     :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));
        jPanel1.add(tf_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 240, 310, 40));
        jPanel1.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(286, 180, 310, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        String loaitk = combobox.getItemAt(combobox.getSelectedIndex());
        sql = new SQLLogin(loaitk);
        list = sql.getListDangNhap(); 
        
        int key = 0 ;
        for(int i=0;i<list.size();i++){
            LoginAccount c = list.get(i);
            if(c.getTenDangNhap().equals(tf_usename.getText())){
                JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập đã tồn tại");
                key = 1;
                break;
            }
        }
        String s1 = tf_pass.getText() ;
        String s2 = tf_pass1.getText() ;
        String s3 = tf_usename.getText() ;
        if(!s1.equals(s2)){
            JOptionPane.showMessageDialog(rootPane, "Hai mật khẩu không trùng khớp !!");
            key = 1;
        }
        if(key == 0){
            LoginAccount x = new LoginAccount() ;
            x.setTenDangNhap(s3);
            x.setMatKhau(s1);
            x.setLoaiTK(loaitk);
            try {
                if(sql.addDangNhap(x)){
                    JOptionPane.showMessageDialog(rootPane, "Tạo tài khoản thành công !!");
                    list.add(x);
                    try {
                        Thread.sleep(500);
                        setVisible(false);
                        new LoginJFrame().setVisible(true);
                    } catch (Exception e) {}
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Lỗi !!!");
                }   
            }catch (Exception ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi !!!");
                ex.printStackTrace();
            }  
        }     
    }//GEN-LAST:event_b_loginActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        this.setVisible(false);
        new LoginJFrame().setVisible(true);
    }//GEN-LAST:event_jLabel7MouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_login;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JPasswordField tf_pass1;
    private javax.swing.JTextField tf_usename;
    // End of variables declaration//GEN-END:variables
}
